### ISSUE TITLE
Update 'stats' package to use new Provider API.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/instrumentation-java#151]
We should update all code that calls `Provider.newInstance` to call `Provider.createInstance` instead.  `createInstance` works well with shading and Android.

`newInstance`:
https://github.com/google/instrumentation-java/blob/1435c7fdf4be28ef724350558be6984f39d386c8/core/src/main/java/com/google/instrumentation/common/Provider.java#L39

`createInstance`:
https://github.com/google/instrumentation-java/blob/1435c7fdf4be28ef724350558be6984f39d386c8/core/src/main/java/com/google/instrumentation/common/Provider.java#L65

**Comment by bogdandrutu** [comment]
https://github.com/census-instrumentation/instrumentation-java/pull/360
