### ISSUE TITLE
Integrate with gRPC Context

### ISSUE THREAD

**Issue by zhangkun83** [census-instrumentation/instrumentation-java#5]
Currently `CensusContext.setCurrent()` sets itself to the thread-local.  I think it should attach to the current gRPC context instead.  Perhaps it needs a new name. How about this:

``` java
abstract class CensusContext {
  // Returns a new gRPC Context based on current Context, with the CensusContext attach to it
  Context attach();
}
```

`getCurrent()` would be changed to retrieve from current gRPC `Context`, instead of from thread-local.

The typical usage on the server-side would be:

``` java
CensusContext cc = censusContextFactory.deserialize(censusContextBytes);
Context ctx = cc.attach();
executor.execute(new ContextRunnable(ctx) {
  // In this method, current Context is "ctx".
  @Override
  public void runInContext() {
    // run the RPC handler
    ...
    // at the end of the RPC
    CensusContext cc = censusContextFactory.getCurrent();  // retrives from current Context
    cc.record(...);
  }
});
```

**Comment by adriancole** [comment]
looks reasonable

**Comment by adriancole** [comment]
cc @schlosna @ewhauser I think we should do something similar in brave and just use GRPC's context library

**Comment by zhangkun83** [comment]
FYI The Context artifact has been uploaded as "io.grpc:grpc-context:1.0.1". It should show up in Maven repos soon.

**Comment by sebright** [comment]
gRPC context integration for stats was added in #299 and #305.
