### ISSUE TITLE
Consider generating value classes with AutoValue.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/instrumentation-java#79]
We could probably generate a significant number of the classes under `core/java/com/google/instrumentation/` using [AutoValue](https://github.com/google/auto/tree/master/value).  It would reduce boilerplate, but it might complicate the build.

**Comment by adriancole** [comment]
I'm pretty happy with auto-value, it also has a memoized feature which
could come in handy

**Comment by sebright** [comment]
#132 applied AutoValue to two classes, but I'm leaving this open until we convert the rest of the value classes.

**Comment by bogdandrutu** [comment]
We've already switched a lot of the classes and this become a common thing. No need to keep this issue around.
